# Generated by Django 4.2.7 on 2023-11-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reguser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=20)),
                ('password', models.EmailField(max_length=20)),
            ],
        ),
    ]
