# Generated by Django 4.2.7 on 2023-11-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_reguser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='status',
            field=models.CharField(default='active', max_length=20),
            preserve_default=False,
        ),
    ]
