# Generated by Django 4.2.7 on 2023-11-20 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reguser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reguser',
            name='status',
        ),
    ]
