# Generated by Django 4.2.7 on 2023-12-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_compdance_compmusic'),
    ]

    operations = [
        migrations.AddField(
            model_name='compdance',
            name='profile',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='compmusic',
            name='profile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
