# Generated by Django 4.2.7 on 2023-12-12 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_compdance_profile_compmusic_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('projectimage', models.FileField(max_length=20, upload_to='')),
                ('client', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('projectdetail', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.compmusic')),
            ],
        ),
    ]
