# Generated by Django 4.2.7 on 2023-12-12 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='username',
        ),
        migrations.AddField(
            model_name='project',
            name='dname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.compdance'),
        ),
        migrations.AddField(
            model_name='project',
            name='mname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.compmusic'),
        ),
    ]
