# Generated by Django 4.2.7 on 2023-12-12 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_project_username_project_dname_project_mname'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bdate', models.DateField()),
                ('price', models.IntegerField()),
                ('dis', models.TextField()),
                ('address', models.TextField()),
                ('dname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.compdance')),
                ('mname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.compmusic')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.reguser')),
            ],
        ),
    ]
