# Generated by Django 4.2.7 on 2023-12-14 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special', models.CharField(max_length=40, null=True)),
                ('native', models.CharField(max_length=40)),
                ('achievements', models.CharField(max_length=40, null=True)),
                ('fprice', models.IntegerField()),
                ('dname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.compdance')),
                ('mname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.compmusic')),
            ],
        ),
    ]
