# Generated by Django 4.2.7 on 2023-12-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='disc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
