# Generated by Django 4.2.7 on 2023-12-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_about_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='experience',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
