# Generated by Django 4.2.7 on 2023-12-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_about_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='experience',
            field=models.IntegerField(null=True),
        ),
    ]
