# Generated by Django 4.2.7 on 2023-12-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_about_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='experience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
