# Generated by Django 4.2.7 on 2023-12-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_about_disc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='fprice',
            field=models.IntegerField(null=True),
        ),
    ]
