# Generated by Django 4.2.7 on 2024-01-13 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_about_fprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_success',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.CharField(default=False, max_length=10)),
                ('user_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.booking')),
            ],
        ),
    ]
