# Generated by Django 4.2.7 on 2024-01-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_payment_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.CharField(default='Not Paid', max_length=10),
        ),
        migrations.DeleteModel(
            name='payment_success',
        ),
    ]
