# Generated by Django 4.2.7 on 2024-01-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_reguser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='profile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
